# Generated by Django 3.1.3 on 2020-11-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_login',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
